In [3]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"CUDA version: {torch.version.cuda}")
    print(f"Number of GPYUs: {torch.cuda.device_count()}")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
    print("GPU is not available")
    print("Using CPU")

GPU is not available
Using CPU


# Creating a Tensor

### 1. Using Empty

In [3]:
# Using Empty
# torch.empty() creates a tensor with uninitialized data

# torch.empty(2, 3)
a = torch.empty(2, 3)
print(a)
type(a)
print(f"Type of a: {a.dtype}")
print()


# torch.empty(2, 3, dtype=torch.float64)
b = torch.empty(2, 3)
print(b)
type(b)
print(f"Type of b: {b.dtype}")
print()

# torch.empty(2, 3, dtype=torch.int32)
c = torch.empty(2, 3, dtype=torch.int32)
print(c)
type(c)
print(f"Type of b: {c.dtype}")
print()

tensor([[7.6020e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])
Type of a: torch.float32

tensor([[5.5858e-14, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.5607e-14, 0.0000e+00]])
Type of b: torch.float32

tensor([[708864014,         0,         0],
        [        0,         0,         0]], dtype=torch.int32)
Type of b: torch.int32



### 2. Using Zeros

In [4]:
a = torch.zeros(2, 3)
print(a)
print(f"Type of a: {a.dtype}")
print()

b = torch.zeros(2, 3, dtype=torch.float64)
print(b)
print(f"Type of a: {b.dtype}")
print()

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type of a: torch.float32

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
Type of a: torch.float64



### 3. Using ones


In [5]:
a = torch.ones(2, 3)
print(a)
print(f"Type of a: {a.dtype}")
print()

b = torch.ones(2, 3, dtype=torch.float64)
print(b)
print(f"Type of a: {b.dtype}")
print()

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type of a: torch.float32

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
Type of a: torch.float64



### 4. Using rand

In [6]:
# Always use torch.rand() to create a tensor with random values
# torch.rand() creates a tensor with random values
a = torch.rand(2, 3)
print(a)
print(f"Type of a: {a.dtype}")
print()

b = torch.rand(2, 3, dtype=torch.float64)
print(b)
print(f"Type of a: {b.dtype}")
print()


tensor([[0.6598, 0.8759, 0.2131],
        [0.6149, 0.0900, 0.7302]])
Type of a: torch.float32

tensor([[0.4197, 0.2955, 0.4449],
        [0.6132, 0.0473, 0.8456]], dtype=torch.float64)
Type of a: torch.float64



### 5. manual_seed

In [7]:
# Always use torch.manual_seed() to set the random seed
# torch.manual_seed(0) sets the random seed

torch.manual_seed(100)

a = torch.rand(2, 3)
print(a)
print(f"Type of a: {a.dtype}")
print()


b = torch.rand(2, 3, dtype=torch.float64)
print(b)
print(f"Type of a: {b.dtype}")
print()


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
Type of a: torch.float32

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)
Type of a: torch.float64



### 6. Using arange

In [8]:
# torch.arange() creates a 1D tensor with values from start to end
a = torch.arange(1, 10)
print(a)
print(f"Type of a: {a.dtype}")
print()

#  2d tensor
b = torch.arange(1, 10).reshape(3, 3)
print(b)
print()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Type of a: torch.int64

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])



### 7. Using tensor

In [9]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)
print()
print(f"Type of a: {a.dtype}")
print()

tensor([[1, 2, 3],
        [4, 5, 6]])

Type of a: torch.int64



### 8. Other ways


In [10]:
# using linspace
a = torch.linspace(1, 10, steps=5)
print("Using linspacec: ", a)

b = torch.linspace(1, 10, 5)
print("Using linspace: " ,b)

print()

# using logspace
c = torch.logspace(1, 10, 5)
print("Usinf logspace: ",c)
print()

# using eye
d = torch.eye(5)
print("Using eye: ", d)
print()

# using full
e = torch.full((2, 3), 5)
print("Using full: ", e)

# using full_like
f = torch.full_like(a, 5)
print("Using full_like: ", f)


Using linspacec:  tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
Using linspace:  tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

Usinf logspace:  tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])

Using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Using full:  tensor([[5, 5, 5],
        [5, 5, 5]])
Using full_like:  tensor([5., 5., 5., 5., 5.])


# Tensor Shapes


In [11]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066966817751969077, 3977868362401855793, 6500725275829417006]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
# torch.rand_like(x)  ##RuntimeError: "check_uniform_bounds" not implemented for 'Long'

torch.rand_like(x, dtype=torch.float64)

tensor([[0.7911, 0.4274, 0.4460],
        [0.5522, 0.9559, 0.9405]], dtype=torch.float64)

# Tensor Data Types

In [17]:
# find the data type
x.dtype

torch.int64

In [18]:
# Assign a data type
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [19]:
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [20]:
#  using to()(
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

### 1.  Scalar Operation

In [21]:
x = torch.rand(2, 2)
x


tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])

In [22]:
# Addition
x + 2
print("Addition: ", x + 2)
print()

# Subtraction
x - 2
print("Subtraction: ", x - 2)
print()

# Multiplication
x * 2
print("Multiplication: ", x * 2)
print()

# Division
x / 3
print("Division: ", x / 3)
print()

# Integer Division
(x * 100) // 3
print("Integer Division: ", (x * 100) // 3)
print()

# Modulus
((x * 100) // 3) % 2
print("Modulus: ", ((x * 100) // 3) % 2)
print()

# Power
x ** 2
print("Power: ", x ** 2)


Addition:  tensor([[2.5277, 2.2472],
        [2.7909, 2.4235]])

Subtraction:  tensor([[-1.4723, -1.7528],
        [-1.2091, -1.5765]])

Multiplication:  tensor([[1.0554, 0.4944],
        [1.5818, 0.8470]])

Division:  tensor([[0.1759, 0.0824],
        [0.2636, 0.1412]])

Integer Division:  tensor([[17.,  8.],
        [26., 14.]])

Modulus:  tensor([[1., 0.],
        [0., 0.]])

Power:  tensor([[0.2785, 0.0611],
        [0.6255, 0.1793]])


### 2. Element wise Operations 

# ⚡ Element-wise Operations in PyTorch (Research Guide)

Element-wise operations apply a function to each individual element of one or more tensors. These operations are foundational in deep learning for vectorized computation.

---

## 🔹 1. Arithmetic Element-wise Operations

| Operation      | PyTorch Function             | Example                           |
|----------------|------------------------------|-----------------------------------|
| Addition       | `torch.add`, `+`             | `a + b`                           |
| Subtraction    | `torch.sub`, `-`             | `a - b`                           |
| Multiplication | `torch.mul`, `*`             | `a * b`                           |
| Division       | `torch.div`, `/`             | `a / b`                           |
| Floor Division | `torch.floor_divide`, `//`   | `a // b`                          |
| Modulus        | `torch.remainder`, `%`       | `a % b`                           |
| Power          | `torch.pow`, `**`            | `a ** b`                          |

```
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])
print(a + b)  # tensor([5., 7., 9.])
```

---

## 🔹 2. Comparison Element-wise Operations

| Operation           | PyTorch Function       | Example             |
|---------------------|------------------------|---------------------|
| Equal               | `torch.eq`             | `a == b`            |
| Not Equal           | `torch.ne`             | `a != b`            |
| Greater Than        | `torch.gt`             | `a > b`             |
| Greater or Equal    | `torch.ge`             | `a >= b`            |
| Less Than           | `torch.lt`             | `a < b`             |
| Less or Equal       | `torch.le`             | `a <= b`            |

Returns a Boolean tensor (`torch.bool` dtype).

---

## 🔹 3. Logical Element-wise Operations

| Operation      | PyTorch Function     | Description                        |
|----------------|----------------------|------------------------------------|
| AND            | `torch.logical_and`  | Element-wise logical AND           |
| OR             | `torch.logical_or`   | Element-wise logical OR            |
| XOR            | `torch.logical_xor`  | Element-wise logical XOR           |
| NOT            | `torch.logical_not`  | Element-wise logical NOT           |

---

## 🔹 4. Trigonometric and Exponential Element-wise Ops

| Function              | Description                        |
|-----------------------|------------------------------------|
| `torch.sin`, `cos`, `tan`       | Trigonometric functions           |
| `torch.asin`, `acos`, `atan`    | Inverse trigonometric             |
| `torch.exp`, `torch.log`        | Exponential and logarithm         |
| `torch.sqrt`, `torch.rsqrt`     | Square root, reciprocal sqrt      |
| `torch.abs`                     | Absolute value                    |
| `torch.ceil`, `floor`, `round`  | Rounding functions                |
| `torch.clamp(x, min, max)`      | Clamp values within range         |
| `torch.sigmoid`, `tanh`, `relu` | Common activation functions       |

---

## 🔹 5. Bitwise Element-wise Operations (on integers)

| Operation      | PyTorch Function     |
|----------------|----------------------|
| AND            | `torch.bitwise_and`  |
| OR             | `torch.bitwise_or`   |
| XOR            | `torch.bitwise_xor`  |
| NOT            | `torch.bitwise_not`  |
| Left Shift     | `torch.bitwise_left_shift` |
| Right Shift    | `torch.bitwise_right_shift` |

---

## 🔹 6. Broadcasting in Element-wise Ops

PyTorch supports **broadcasting**, which allows element-wise ops between tensors of different shapes under certain conditions.

```
a = torch.tensor([[1], [2], [3]])  # Shape: [3, 1]
b = torch.tensor([10, 20, 30])     # Shape: [3]
c = a * b  # Broadcasting to shape [3, 3]
```

---

## 🔹 7. In-place Element-wise Ops (Memory Efficient)

Use `_` suffix to perform operation in-place.

| Operation | In-place Function     |
|-----------|------------------------|
| Add       | `a.add_(b)`            |
| Subtract  | `a.sub_(b)`            |
| Multiply  | `a.mul_(b)`            |
| Divide    | `a.div_(b)`            |

> ⚠️ Note: In-place ops can interfere with autograd if used improperly.

---

## 🧠 Summary Table

| Category       | Common Ops                              |
|----------------|------------------------------------------|
| Arithmetic     | `+`, `-`, `*`, `/`, `**`, `torch.pow`    |
| Comparison     | `torch.eq`, `ne`, `gt`, `lt`, etc.       |
| Logical        | `logical_and`, `or`, `xor`, `not`        |
| Trigonometric  | `sin`, `cos`, `tan`, `exp`, `log`, etc.  |
| Bitwise        | `bitwise_and`, `or`, `not`, `xor`        |
| In-place Ops   | `add_`, `mul_`, etc.                     |
| Broadcasting   | Auto-expand for compatible shapes        |

---

> ✅ These operations are **highly optimized** and essential for **deep learning model development**, **data manipulation**, and **loss computations**.

```

In [23]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print()
print(b)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])


In [24]:
# Addition
print(f"Addition of a and b is : {a + b}")
print()

# Subtraction
print(f"Subtraction of a and b is : {a - b}")
print()

# Multiplication
print(f"Multiplication of a and b is : {a * b}")
print()

# Division
print(f"Division of a and b is : {a / b}")
print()

# Power
print(f"Power : {a ** b}")
print()

# Modulus
print(f"Modulus of a and b is : {a % b}")
print()


Addition of a and b is : tensor([[0.5332, 0.2568, 1.6012],
        [1.0494, 0.4811, 1.4163]])

Subtraction of a and b is : tensor([[-0.4994,  0.1850,  0.3059],
        [ 0.3634, -0.1554,  0.3641]])

Multiplication of a and b is : tensor([[0.0087, 0.0079, 0.6175],
        [0.2423, 0.0518, 0.4683]])

Division of a and b is : tensor([[0.0327, 6.1557, 1.4723],
        [2.0593, 0.5118, 1.6921]])

Power : tensor([[0.1216, 0.9473, 0.9697],
        [0.8876, 0.5613, 0.9406]])

Modulus of a and b is : tensor([[0.0169, 0.0056, 0.3059],
        [0.0204, 0.1629, 0.3641]])



In [25]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [26]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
# negative
torch.negative(c)

tensor([-1,  2, -3,  4])

In [28]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [29]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [30]:
# ceil - greater integer
print(d)
torch.ceil(d)

tensor([1.9000, 2.3000, 3.7000, 4.4000])


tensor([2., 3., 4., 5.])

In [31]:
# floor - smaller integer
print(d)
torch.floor(d)

tensor([1.9000, 2.3000, 3.7000, 4.4000])


tensor([1., 2., 3., 4.])

In [32]:
# clamp - put numbers within a range
# this is called clamping operation
print(d)
torch.clamp(d, min=2, max=3)

tensor([1.9000, 2.3000, 3.7000, 4.4000])


tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction Operation

## 🧠 PyTorch Reduction Operations – Complete Guide

In PyTorch, **reduction operations** condense tensors along one or more dimensions into a **single value or lower-dimensional tensor**. These are often used in **loss computation**, **statistics**, **summaries**, and **aggregation in models**.

---

### 🔹 Categories of Reduction Operations

| Category             | Examples |
|----------------------|----------|
| **Summation-based**  | `sum`, `mean`, `prod`, `cumsum`, `cumprod` |
| **Min/Max-based**    | `min`, `max`, `argmin`, `argmax`, `amin`, `amax` |
| **Norm-based**       | `norm`, `frobenius_norm`, `nuclear_norm` |
| **Statistical**      | `std`, `var`, `median`, `quantile`, `mode` |
| **Logical**          | `all`, `any` |
| **Others**           | `logsumexp`, `count_nonzero`, `unique`, `kthvalue`, `topk` |

---

### 🔹 1. **Summation-Based Reductions**

| Function | Description |
|----------|-------------|
| `torch.sum(input, dim)` | Sum of elements across dimensions |
| `torch.mean(input, dim)` | Mean of elements |
| `torch.prod(input, dim)` | Product of elements |
| `torch.cumsum(input, dim)` | Cumulative sum |
| `torch.cumprod(input, dim)` | Cumulative product |

🔸 Example:
```python
x = torch.tensor([[1, 2], [3, 4]])
torch.sum(x, dim=0)  # tensor([4, 6])
```

---

### 🔹 2. **Min/Max-Based Reductions**

| Function | Description |
|----------|-------------|
| `torch.min`, `torch.max` | Returns min/max (optionally along dim) |
| `torch.amin`, `torch.amax` | Same as min/max but works element-wise |
| `torch.argmin`, `torch.argmax` | Indices of min/max values |
| `torch.clamp(input, min, max)` | Bounds values between min and max |
| `torch.kthvalue(input, k, dim)` | k-th smallest value and index |
| `torch.topk(input, k, dim)` | Top-k largest values and indices |

🔸 Example:
```python
x = torch.tensor([1, 3, 2])
torch.topk(x, 2)  # values=tensor([3, 2]), indices=tensor([1, 2])
```

---

### 🔹 3. **Norm-Based Reductions**

| Function | Description |
|----------|-------------|
| `torch.norm(input, p='fro')` | Vector or matrix norm |
| `torch.linalg.vector_norm`, `matrix_norm` | Explicit norm functions |
| `torch.nn.functional.normalize()` | Normalizes tensor (unit norm) |

🔸 Example:
```python
torch.norm(torch.tensor([3.0, 4.0]))  # 5.0 (Euclidean norm)
```

---

### 🔹 4. **Statistical Reductions**

| Function | Description |
|----------|-------------|
| `torch.std(input, dim)` | Standard deviation |
| `torch.var(input, dim)` | Variance |
| `torch.median(input)` | Median value |
| `torch.mode(input)` | Most frequent element |
| `torch.quantile(input, q)` | q-th quantile value |

🔸 Example:
```python
x = torch.tensor([1., 2., 3., 4.])
torch.quantile(x, 0.5)  # Median → 2.5
```

---

### 🔹 5. **Logical Reductions**

| Function | Description |
|----------|-------------|
| `torch.all(input, dim)` | True if all elements are true |
| `torch.any(input, dim)` | True if any element is true |

🔸 Example:
```
x = torch.tensor([True, False])
torch.all(x)  # False
```

---

### 🔹 6. **Other Reductions**

| Function | Description |
|----------|-------------|
| `torch.logsumexp(input, dim)` | Stable `log(sum(exp(x)))` – useful in softmax/logits |
| `torch.count_nonzero(input)` | Number of non-zero elements |
| `torch.unique(input)` | Unique elements |
| `torch.numel(input)` | Total number of elements in a tensor |
| `torch.bincount(input)` | Histogram of counts for 1D int tensor |

---

### ✅ Choosing the Right Reduction

| Task Type        | Recommended Reductions |
|------------------|------------------------|
| Classification   | `torch.mean`, `torch.argmax`, `torch.nn.CrossEntropyLoss` |
| Statistical ML   | `torch.var`, `torch.std`, `torch.median` |
| NLP (Logits)     | `torch.logsumexp`, `torch.softmax` |
| Image Segmentation | `torch.count_nonzero`, `torch.sum` over masks |
| Attention Mechanisms | `torch.topk`, `torch.softmax`, `torch.mean` |

---

### 📌 Summary Chart

```
+----------------+------------------------------------------+
| Function       | Use Case                                |
+----------------+------------------------------------------+
| sum / mean     | General aggregation                      |
| min / max      | Boundary values                          |
| argmin / argmax| Label prediction                         |
| std / var      | Spread of data                           |
| norm           | Distance measures, regularization        |
| logsumexp      | Numerical stability in log space         |
| topk           | Ranking or attention scores              |
| count_nonzero  | Mask operations                          |
+----------------+------------------------------------------+
```

---


In [33]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=float)
e

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

In [34]:
# sum
print(e)
print()

print(f"Sum of tensor is : {torch.sum(e)}")
print()

# sum along columns
print(f"Sum of tensor along columns is : {torch.sum(e, dim=0)}")
print()

# sum along rows
print(f"Sum of tensor along rows is : {torch.sum(e, dim=1)}")



tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Sum of tensor is : 47.0

Sum of tensor along columns is : tensor([14., 16., 17.], dtype=torch.float64)

Sum of tensor along rows is : tensor([22., 25.], dtype=torch.float64)


In [35]:
# mean works only with floating point or complex dtype

# mean
print(e)
print()

print(f"Mean of tensor is : {torch.mean(e)}")
print()

# mean along columns
print(f"Mean of tensor along columns is : {torch.mean(e, dim=0)}")
print()

# mean along rows
print(f"Mean of tensor along rows is : {torch.mean(e, dim=1)}")


tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Mean of tensor is : 7.833333333333333

Mean of tensor along columns is : tensor([7.0000, 8.0000, 8.5000], dtype=torch.float64)

Mean of tensor along rows is : tensor([7.3333, 8.3333], dtype=torch.float64)


In [36]:
# Median
print(e)
print()

print(f"Median of tensor is : {torch.median(e)}")
print()

# Median along columns
print(f"Median of tensor along columns is : {torch.median(e, dim=0)}")
print()

# Median along rows
print(f"Median of tensor along rows is : {torch.median(e, dim=1)}")


tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Median of tensor is : 8.0

Median of tensor along columns is : torch.return_types.median(
values=tensor([5., 7., 8.], dtype=torch.float64),
indices=tensor([0, 1, 0]))

Median of tensor along rows is : torch.return_types.median(
values=tensor([8., 9.], dtype=torch.float64),
indices=tensor([2, 0]))


In [37]:
# max 
print(e)
print()

print(f"Maximum of tensor is : {torch.max(e)}")
print()

# max along columns
print(f"Maximum of tensor along columns is : {torch.max(e, dim=0)}")
print()

# max along rows
print(f"Maximum of tensor along rows is : {torch.max(e, dim=1)}")

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Maximum of tensor is : 9.0



Maximum of tensor along columns is : torch.return_types.max(
values=tensor([9., 9., 9.], dtype=torch.float64),
indices=tensor([1, 0, 1]))

Maximum of tensor along rows is : torch.return_types.max(
values=tensor([9., 9.], dtype=torch.float64),
indices=tensor([1, 0]))


In [38]:
# min 
print(e)
print()

print(f"Minimum of tensor is : {torch.min(e)}")
print()

# min along columns
print(f"Minimum of tensor along columns is : {torch.min(e, dim=0)}")
print()

# min along rows
print(f"Minimum of tensor along rows is : {torch.min(e, dim=1)}")

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Minimum of tensor is : 5.0

Minimum of tensor along columns is : torch.return_types.min(
values=tensor([5., 7., 8.], dtype=torch.float64),
indices=tensor([0, 1, 0]))

Minimum of tensor along rows is : torch.return_types.min(
values=tensor([5., 7.], dtype=torch.float64),
indices=tensor([0, 1]))


In [39]:
# product (prod) 
print(e)
print()

print(f"Product of tensor is : {torch.prod(e)}")
print()

# product along columns
print(f"Product of tensor along columns is : {torch.prod(e, dim=0)}")
print()

# product along rows
print(f"Product of tensor along rows is : {torch.prod(e, dim=1)}")

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Product of tensor is : 204120.0

Product of tensor along columns is : tensor([45., 63., 72.], dtype=torch.float64)

Product of tensor along rows is : tensor([360., 567.], dtype=torch.float64)


In [40]:
# Standaed deviation
print(e)
print()

print(f"Standaed deviation of tensor is : {torch.std(e)}")
print()

# Standaed deviation along columns
print(f"Standaed deviation of tensor along columns is : {torch.std(e, dim=0)}")
print()

# Standaed deviation along rows
print(f"Standaed deviation of tensor along rows is : {torch.std(e, dim=1)}")

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Standaed deviation of tensor is : 1.6020819787597222

Standaed deviation of tensor along columns is : tensor([2.8284, 1.4142, 0.7071], dtype=torch.float64)

Standaed deviation of tensor along rows is : tensor([2.0817, 1.1547], dtype=torch.float64)


In [41]:
# Variance
print(e)
print()

print(f"Variance of tensor is : {torch.var(e)}")
print()

# Variance along columns
print(f"Variance of tensor along columns is : {torch.var(e, dim=0)}")
print()

# Variance along rows
print(f"Variance of tensor along rows is : {torch.var(e, dim=1)}")

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Variance of tensor is : 2.5666666666666673

Variance of tensor along columns is : tensor([8.0000, 2.0000, 0.5000], dtype=torch.float64)

Variance of tensor along rows is : tensor([4.3333, 1.3333], dtype=torch.float64)


In [42]:
# argmax - give position of the largest number
print(e)
print()

print(f"Variance of tensor is : {torch.argmax(e)}")
print()

# argmax along columns
print(f"argmax of tensor along columns is : {torch.argmax(e, dim=0)}")
print()

# argmax along rows
print(f"argmax of tensor along rows is : {torch.argmax(e, dim=1)}")

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)



Variance of tensor is : 1

argmax of tensor along columns is : tensor([1, 0, 1])

argmax of tensor along rows is : tensor([1, 0])


In [43]:
# argmin - give position of the largest number
print(e)
print()

print(f"Variance of tensor is : {torch.argmin(e)}")
print()

# argmin along columns
print(f"argmax of tensor along columns is : {torch.argmin(e, dim=0)}")
print()

# argmin along rows
print(f"argmax of tensor along rows is : {torch.argmin(e, dim=1)}")

tensor([[5., 9., 8.],
        [9., 7., 9.]], dtype=torch.float64)

Variance of tensor is : 0

argmax of tensor along columns is : tensor([0, 1, 0])

argmax of tensor along rows is : tensor([0, 1])


### 4. Matrix Operation

# 🧮 Matrix Operations in PyTorch (Research-level Guide)

PyTorch provides powerful and efficient APIs for matrix operations, supporting high-performance computation on both CPU and GPU.

---

## 🔹 1. Matrix Creation

```
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[5., 6.], [7., 8.]])
```

---

## 🔹 2. Basic Matrix Arithmetic

| Operation        | Function / Syntax   | Description                  |
|------------------|---------------------|------------------------------|
| Addition         | `A + B` or `torch.add(A, B)` | Element-wise addition       |
| Subtraction      | `A - B`             | Element-wise subtraction     |
| Scalar Multiplication | `A * 2`        | Each element multiplied by scalar |
| Element-wise Multiplication | `A * B`  | Element-wise product         |
| Division         | `A / B`             | Element-wise division        |

---

## 🔹 3. Matrix Multiplication

### 🟠 Matrix Product (Dot Product)

```
torch.matmul(A, B)
A @ B  # Equivalent
```

- Performs matrix multiplication.
- Requires shape compatibility: `(m x n) @ (n x p) → (m x p)`

### 🟠 Batch Matrix Multiplication

```
torch.bmm(A, B)  # For 3D tensors (batch_size, n, m)
```

---

## 🔹 4. Transpose and Reshape

| Operation      | Function                    |
|----------------|-----------------------------|
| Transpose      | `A.T` or `torch.transpose(A, 0, 1)` |
| Reshape        | `A.view(new_shape)`         |
| Permute dims   | `A.permute(dim1, dim2, ...)`|
| Squeeze        | `A.squeeze()`               |
| Unsqueeze      | `A.unsqueeze(dim)`          |

```
A.T  # Transpose of A
A.view(4)  # Reshape to 1D
```

---

## 🔹 5. Determinant, Inverse & Rank

| Operation        | Function                |
|------------------|-------------------------|
| Determinant      | `torch.linalg.det(A)`   |
| Inverse          | `torch.linalg.inv(A)`   |
| Matrix Rank      | `torch.linalg.matrix_rank(A)` |
| Pseudo-inverse   | `torch.linalg.pinv(A)`  |

```
torch.linalg.inv(A)  # Inverse of matrix A
```

---

## 🔹 6. Eigenvalues, Eigenvectors & Decompositions

| Operation           | Function                    |
|---------------------|-----------------------------|
| Eigenvalues/Vectors | `torch.linalg.eig(A)`       |
| SVD (Singular Value Decomposition) | `torch.linalg.svd(A)` |
| QR Decomposition     | `torch.linalg.qr(A)`        |
| Cholesky (if SPD)    | `torch.linalg.cholesky(A)`  |

```
eigenvalues, eigenvectors = torch.linalg.eig(A)
```

---

## 🔹 7. Special Matrix Ops

| Operation          | Function                    |
|--------------------|-----------------------------|
| Identity Matrix     | `torch.eye(n)`             |
| Diagonal Matrix     | `torch.diag(input)`        |
| Trace (sum of diag) | `torch.trace(A)`           |
| Outer Product       | `torch.ger(a, b)` or `a.unsqueeze(1) @ b.unsqueeze(0)` |
| Kronecker Product   | `torch.kron(A, B)`         |

---

## 🔹 8. Broadcasting in Matrix Ops

PyTorch supports **broadcasting** similar to NumPy:
```
A = torch.randn(3, 1)
B = torch.randn(1, 4)
C = A * B  # Result: shape (3, 4)
```

---

## 🔹 9. Matrix Norms

| Operation       | Function                        |
|-----------------|----------------------------------|
| Frobenius Norm  | `torch.norm(A)`                 |
| p-Norm          | `torch.norm(A, p=1/2/∞)`         |

---

## 🧠 Summary

| Task                  | PyTorch Function            |
|-----------------------|-----------------------------|
| Matrix Multiply       | `torch.matmul`, `@`         |
| Transpose             | `.T`                        |
| Inverse               | `torch.linalg.inv`          |
| Determinant           | `torch.linalg.det`          |
| SVD                   | `torch.linalg.svd`          |
| Eigen decomposition   | `torch.linalg.eig`          |
| Identity Matrix       | `torch.eye`                 |
| Diagonal              | `torch.diag`                |
| Trace                 | `torch.trace`               |

---

> ✅ PyTorch’s matrix APIs are optimized with BLAS/LAPACK backend, and can be accelerated on CUDA (GPU) for large-scale computations.

```



In [44]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f"f: {f}")
print()
print(f"g: {g}")


f: tensor([[2, 6, 7],
        [7, 8, 3]])

g: tensor([[6, 1],
        [5, 5],
        [0, 4]])


In [45]:
# matrix multiplication
torch.matmul(f, g)

tensor([[42, 60],
        [82, 59]])

In [46]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

print(f"vector1: {vector1}")
print()
print(f"vector2: {vector2}")

vector1: tensor([1, 2])

vector2: tensor([3, 4])


In [47]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [48]:
# transpose
print(f"f: {f}")
print()

torch.transpose(f, 0, 1)

f: tensor([[2, 6, 7],
        [7, 8, 3]])



tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [49]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [50]:
# determinant
torch.det(h)

tensor(-6.)

In [51]:
# inverse
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

### 5. Comparison Operations

# 🔍 Comparison Operations in PyTorch

PyTorch supports a wide variety of **element-wise** comparison operations. These are essential for tasks like masking, conditional logic, filtering tensors, and more.

---

## 🔹 1. Element-wise Comparison Operators

| Operation               | Syntax / Function                  | Description                         |
|-------------------------|------------------------------------|-------------------------------------|
| Equal                   | `A == B` or `torch.eq(A, B)`       | Checks if elements of A and B are equal |
| Not Equal               | `A != B` or `torch.ne(A, B)`       | Checks if elements are not equal     |
| Greater Than            | `A > B` or `torch.gt(A, B)`        | Checks if A elements are greater than B |
| Greater Than or Equal   | `A >= B` or `torch.ge(A, B)`       | Checks if A elements are ≥ B         |
| Less Than               | `A < B` or `torch.lt(A, B)`        | Checks if A elements are < B         |
| Less Than or Equal      | `A <= B` or `torch.le(A, B)`       | Checks if A elements are ≤ B         |

### 🧪 Example:

```
import torch

A = torch.tensor([1, 2, 3])
B = torch.tensor([2, 2, 1])

A == B  # tensor([False, True, False])
A > B   # tensor([False, False, True])
```

---

## 🔹 2. Logical Comparison on Boolean Tensors

| Operation         | Syntax / Function            | Description                          |
|-------------------|------------------------------|--------------------------------------|
| Logical AND       | `torch.logical_and(A, B)`    | Element-wise AND of boolean tensors |
| Logical OR        | `torch.logical_or(A, B)`     | Element-wise OR                      |
| Logical NOT       | `torch.logical_not(A)`       | Inverts boolean tensor               |
| Logical XOR       | `torch.logical_xor(A, B)`    | Element-wise XOR                     |

```
A = torch.tensor([True, False, True])
B = torch.tensor([False, False, True])

torch.logical_and(A, B)  # tensor([False, False, True])
```

---

## 🔹 3. Functions Returning Boolean Summary

| Function               | Description                                      |
|------------------------|--------------------------------------------------|
| `torch.all(tensor)`    | True if **all** elements are True                |
| `torch.any(tensor)`    | True if **any** element is True                  |
| `torch.isclose(A, B)`  | True if elements of A and B are close (within tolerance) |
| `torch.equal(A, B)`    | True if **all elements and shapes** are equal   |
| `torch.allclose(A, B)` | True if all elements are close within tolerance |

```
torch.all(torch.tensor([True, True]))       # True
torch.any(torch.tensor([False, True]))      # True
torch.isclose(torch.tensor([1.0]), torch.tensor([1.0001]), rtol=1e-3)  # True
```

---

## 🔹 4. Masking with Comparison Ops

You can use comparison results to mask tensors:

```
A = torch.tensor([10, 20, 30, 40])
mask = A > 25
filtered = A[mask]  # tensor([30, 40])
```

---

## 🔹 5. Type of Result

- All comparison operations return a `torch.bool` tensor of the same shape.

---

## 🔹 6. Note on Broadcasting

All comparison operations **support broadcasting** just like arithmetic operations:

```
A = torch.tensor([[1], [2], [3]])  # Shape (3,1)
B = torch.tensor([2, 2, 2])        # Shape (3,)

result = A > B  # Broadcasts and compares
```

---

## 🧠 Summary Table

| Operation   | Function          |
|-------------|-------------------|
| Equal       | `==`, `torch.eq`  |
| Not Equal   | `!=`, `torch.ne`  |
| Greater     | `>`,  `torch.gt`  |
| Less        | `<`,  `torch.lt`  |
| Greater Eq  | `>=`, `torch.ge`  |
| Less Eq     | `<=`, `torch.le`  |
| Logical AND | `torch.logical_and` |
| Logical OR  | `torch.logical_or` |
| All True?   | `torch.all`       |
| Any True?   | `torch.any`       |

---

> ✅ Use comparison ops for filtering, condition-based updates, classification thresholds, and tensor validations.

```


In [52]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(f"i : {i}")
print()
print(f"j : {j}")

i : tensor([[0, 8, 4],
        [7, 2, 3]])

j : tensor([[8, 5, 6],
        [2, 9, 5]])


In [53]:
# greater
print(f"i > j : {i > j}")
print()

# less
print(f"i < j : {i < j}")
print()

# greater equal
print(f"i >= j : {i >= j}")
print()

# less equal
print(f"i <= j : {i <= j}")
print()

# equal
print(f"i == j : {i == j}")
print()

# not equal
print(f"i != j : {i != j}")
print()


i > j : tensor([[False,  True, False],
        [ True, False, False]])

i < j : tensor([[ True, False,  True],
        [False,  True,  True]])

i >= j : tensor([[False,  True, False],
        [ True, False, False]])

i <= j : tensor([[ True, False,  True],
        [False,  True,  True]])

i == j : tensor([[False, False, False],
        [False, False, False]])

i != j : tensor([[True, True, True],
        [True, True, True]])



### 6. Special Functions

# 🌟 Special Functions in PyTorch (`torch.special`)

The `torch.special` module provides **numerically stable**, **scientifically useful** mathematical functions used widely in **scientific computing, statistics, deep learning, and physics**.

These functions include **gamma functions**, **error functions**, **log-sum-exp**, **Bessel functions**, and more.

---

## 🔹 1. Gamma and Related Functions

| Function                  | Description                                          |
|---------------------------|------------------------------------------------------|
| `torch.special.gamma(x)` | Computes the Gamma function Γ(x)                     |
| `torch.special.gammaln(x)` | Computes `log(abs(gamma(x)))`                       |
| `torch.special.digamma(x)` | First derivative of `log(gamma(x))`                |
| `torch.special.polygamma(n, x)` | n-th derivative of `log(gamma(x))`           |

📌 **Use Case**: Often used in probabilistic models and distributions.

```
import torch
x = torch.tensor([1.0, 2.0, 3.0])
torch.special.gamma(x)     # tensor([1., 1., 2.])
torch.special.digamma(x)   # tensor([-0.5772, 0.4228, 0.9228])
```

---

## 🔹 2. Error Functions

| Function                  | Description                           |
|---------------------------|---------------------------------------|
| `torch.special.erf(x)`   | Error function                         |
| `torch.special.erfc(x)`  | Complementary error function (1 - erf) |
| `torch.special.erfinv(x)` | Inverse error function                |

📌 **Use Case**: Used in Gaussian distributions, signal processing, and diffusion models.

```
torch.special.erf(torch.tensor(1.0))    # ≈ 0.8427
torch.special.erfinv(torch.tensor(0.8427))  # ≈ 1.0
```

---

## 🔹 3. Exponential Logarithmic Stability

| Function                         | Description                                      |
|----------------------------------|--------------------------------------------------|
| `torch.special.expit(x)`        | Sigmoid function: 1 / (1 + exp(-x))              |
| `torch.special.logit(x)`        | Inverse of sigmoid (log(x / (1 - x)))            |
| `torch.special.logsumexp(x, dim)` | Stable `log(sum(exp(x)))`                       |

📌 **Use Case**: Useful in classification, loss computation (e.g., softmax-related ops).

```
x = torch.tensor([1.0, 2.0, 3.0])
torch.special.logsumexp(x, dim=0)  # ≈ log(exp(1)+exp(2)+exp(3))
```

---

## 🔹 4. Bessel Functions

| Function                          | Description                         |
|-----------------------------------|-------------------------------------|
| `torch.special.i0(x)`            | Modified Bessel function of the first kind (order 0) |
| `torch.special.i0e(x)`           | Scaled modified Bessel function     |

📌 **Use Case**: Appears in wave equations, signal processing.

```
x = torch.tensor([0.0, 1.0, 2.0])
torch.special.i0(x)
```

---

## 🔹 5. Softmax Variants

| Function                    | Description                                |
|-----------------------------|--------------------------------------------|
| `torch.special.softmax(x, dim)` | Softmax function                       |
| `torch.special.log_softmax(x, dim)` | Log-Softmax function                |

📌 **Use Case**: Classification problems, attention mechanisms, etc.

```
x = torch.tensor([1.0, 2.0, 3.0])
torch.special.softmax(x, dim=0)
```

---

## 🔹 6. Other Special Functions

| Function                         | Description                             |
|----------------------------------|-----------------------------------------|
| `torch.special.ndtr(x)`         | Standard normal cumulative distribution |
| `torch.special.ndtri(x)`        | Inverse of standard normal CDF          |
| `torch.special.multigammaln(x, d)` | Log multivariate gamma function        |
| `torch.special.xlog1py(x, y)`   | Computes `x * log1p(y)` safely          |

---

## 📌 Summary Table

| Category              | Functions                                                                 |
|------------------------|--------------------------------------------------------------------------|
| Gamma Family          | `gamma`, `gammaln`, `digamma`, `polygamma`, `multigammaln`               |
| Error Functions       | `erf`, `erfc`, `erfinv`                                                   |
| Log/Exp Stability     | `expit`, `logit`, `logsumexp`, `xlog1py`                                  |
| Softmax Variants      | `softmax`, `log_softmax`                                                  |
| Bessel Functions      | `i0`, `i0e`                                                                |
| Gaussian/Normal Dist. | `ndtr`, `ndtri`                                                           |

---

## 🧠 Use in Research

- 🧬 **Probabilistic Modeling**: Gamma, digamma, log-gamma functions.
- 📈 **Machine Learning**: Softmax, log-sum-exp, expit/logit for classification & optimization.
- 📊 **Statistical Analysis**: ndtr, ndtri for normal distribution approximations.
- 🧠 **Numerical Stability**: log1p, expit, logsumexp help prevent underflow/overflow.

---

> 🔍 For complete list and doc: [PyTorch Special Functions Docs](https://pytorch.org/docs/stable/special.html)


In [54]:
k = torch.randint(size=(2, 3), low=0, high=10)
k

tensor([[0, 4, 2],
        [7, 1, 1]])

In [55]:
# log
torch.log(k)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000]])

In [56]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [57]:
# sqrt
torch.sqrt(k)


tensor([[0.0000, 2.0000, 1.4142],
        [2.6458, 1.0000, 1.0000]])

In [58]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.8808],
        [0.9991, 0.7311, 0.7311]])

In [59]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [60]:
# softmax is not implemented for int 64, int 32, int 16, int 8

# dim=0 means along columns
# dim=1 means along rows

# softmax along columns
print(f"Softmax along columns : {torch.softmax(k, dim=0)}")
print()

# softmax along rows
print(f"Softmax along rows : {torch.softmax(k, dim=1)}")


Softmax along columns : tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

Softmax along rows : tensor([[0.5761, 0.2119, 0.2119],
        [0.2119, 0.2119, 0.5761]])


In [61]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

# Inplace Operations

# 🔄 In-place Operations in PyTorch

In PyTorch, **in-place operations** directly modify the content of a tensor without making a copy. They are **memory-efficient** but can **interfere with autograd** (automatic differentiation) if not used carefully.

---

## 🔹 How to Identify In-place Operations?

In PyTorch, **in-place methods** end with an exclamation mark (`!`).

> ✅ Example: `tensor.add_(value)` is an in-place version of `tensor.add(value)`

---

## 🔹 Common In-place Operations

| Operation             | In-place Version       | Description                                 |
|-----------------------|------------------------|---------------------------------------------|
| Addition              | `tensor.add_(x)`       | Adds `x` to tensor                          |
| Subtraction           | `tensor.sub_(x)`       | Subtracts `x` from tensor                   |
| Multiplication        | `tensor.mul_(x)`       | Multiplies tensor by `x`                    |
| Division              | `tensor.div_(x)`       | Divides tensor by `x`                       |
| Power                 | `tensor.pow_(x)`       | Raises tensor to power `x`                  |
| Square Root           | `tensor.sqrt_()`       | Computes square root                        |
| Exponential           | `tensor.exp_()`        | Element-wise exponential                    |
| Logarithm             | `tensor.log_()`        | Element-wise log                            |
| Floor                 | `tensor.floor_()`      | Applies floor operation                     |
| Ceil                  | `tensor.ceil_()`       | Applies ceil operation                      |
| Clamp                 | `tensor.clamp_(min, max)` | Clamps values within range              |
| Zeroing              | `tensor.zero_()`       | Sets all values to zero                     |
| Fill                 | `tensor.fill_(x)`      | Fills tensor with value `x`                 |
| Copy                 | `tensor.copy_(other)`  | Copies content from `other` tensor          |
| Normalization        | `tensor.normal_()`     | Fills with samples from normal distribution |
| Uniform              | `tensor.uniform_()`    | Fills with uniform distribution             |

---

## 🔹 Example Code

```
import torch

x = torch.tensor([1.0, 2.0, 3.0])
print("Before:", x)

x.add_(5)
print("After In-place Add:", x)

x.mul_(2)
print("After In-place Multiply:", x)
```

---

## ⚠️ Warning: Use with Caution in Autograd

In-place operations can **overwrite values needed for gradient computation**, causing errors in backpropagation.

```
x = torch.tensor([2.0], requires_grad=True)

y = x * x
y.backward()  # works fine

x.add_(1)     # modifies x in-place — risky for autograd
```

> ⚠️ Prefer out-of-place operations during training unless you're sure of their impact.

---

## ✅ When to Use In-place Ops?

- When memory is limited (e.g., training large models).
- During inference or data preprocessing.
- When gradients are not required (`requires_grad=False`).

---

## 📌 Tips

- All `tensor.function_()` operations are in-place.
- Use `.clone()` if you want to preserve original tensor.
- Avoid using them during model training unless safe.

---

## 🧠 Summary

| Safe For Training? | Use-case                         |
|--------------------|----------------------------------|
| ✅                 | Preprocessing, inference         |
| ❌ (with autograd) | During backpropagation/training  |

---

> 🔍 For more: [PyTorch In-Place Docs](https://pytorch.org/docs/stable/notes/autograd.html#in-place-operations)

---

In [62]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(f"m : {m}")
print()
print(f"n : {n}")

m : tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

n : tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [63]:
m.add_(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [64]:
print(f"m : {m}")
print()
print(f"n : {n}")

m : tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

n : tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [65]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [66]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [67]:
print(f"m : {m}")
print()

m : tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])



# Copying a Tensor

In [68]:
# Copying using assignment operator
a = torch.rand(2, 3)
b = a

print(f"a : {a}")
print()
print(f"b : {b}")

a : tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

b : tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])


In [69]:
a[0][0] = 0

In [70]:
print(f"a : {a}")
print()
print(f"b : {b}")

a : tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

b : tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])


In [71]:
print(f"id of a : {id(a)}")
print()
print(f"id of b : {id(b)}")

# Assignment operator does not create a new tensor, it just creates a reference to the original tensor

id of a : 140047920295488

id of b : 140047920295488


In [72]:
# coping using clone()
b = a.clone()

print(f"a : {a}")
print()
print(f"b : {b}")

a : tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

b : tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])


In [73]:
a[0][0] = 100

In [74]:
print(f"a : {a}")
print()
print(f"b : {b}")

a : tensor([[1.0000e+02, 8.8695e-02, 4.8896e-01],
        [5.8873e-01, 7.3401e-01, 8.4972e-01]])

b : tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])


In [75]:
print(f"id of a : {id(a)}")
print()
print(f"id of b : {id(b)}")


id of a : 140047920295488

id of b : 140047920337120


# Tensor Operations on GPU

# ⚙️ Tensor Operations on GPU in PyTorch

## 🚀 Introduction

PyTorch makes it easy to utilize **GPU acceleration** via CUDA (NVIDIA’s GPU computing toolkit). Using GPU can **significantly boost performance**, especially for deep learning and large matrix computations.

---

## 🔹 Check GPU Availability

```
import torch

# Check if CUDA (GPU) is available
torch.cuda.is_available()
```

---

## 🔹 Set Device

```
# Automatically choose GPU if available, otherwise CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
```

---

## 🔹 Creating Tensors on GPU

```
# Method 1: Create directly on GPU
x = torch.tensor([1.0, 2.0, 3.0], device=device)

# Method 2: Create on CPU, then move to GPU
x = torch.tensor([1.0, 2.0, 3.0])
x = x.to(device)
```

---

## 🔹 Tensor Operations on GPU

Once a tensor is on GPU, any operation you perform on it **stays on GPU**:

```
a = torch.tensor([1.0, 2.0], device=device)
b = torch.tensor([3.0, 4.0], device=device)
c = a + b  # operation on GPU

print(c.device)  # Output: cuda:0
```

---

## 🔹 Moving Between Devices

```
# Move to GPU
x_gpu = x.to("cuda")

# Move back to CPU
x_cpu = x_gpu.to("cpu")
```

---

## 🔹 Allocate Tensors Like Another (Preserving Device)

```
a = torch.ones((2, 2), device=device)
b = torch.zeros_like(a)  # b will also be on the same device as a
```

---

## 🔹 Model on GPU

```
import torch.nn as nn

model = nn.Linear(10, 5)
model.to(device)  # move model to GPU
```

Then move input and targets:

```
input = torch.randn(2, 10).to(device)
output = model(input)
```

---

## 🔹 Performance Comparison (Optional Benchmarking)

```
import time

cpu_tensor = torch.randn(10000, 10000)
gpu_tensor = torch.randn(10000, 10000, device='cuda')

# CPU timing
start = time.time()
_ = cpu_tensor @ cpu_tensor
print("CPU Time:", time.time() - start)

# GPU timing
torch.cuda.synchronize()  # synchronize before timing
start = time.time()
_ = gpu_tensor @ gpu_tensor
torch.cuda.synchronize()
print("GPU Time:", time.time() - start)
```

---

## ⚠️ Notes and Tips

- GPU ops are **asynchronous** by default. Use `torch.cuda.synchronize()` to benchmark accurately.
- Always move **both model and data** to the same device.
- Avoid frequent device switching – it’s **slow and inefficient**.

---

## 🧠 Summary

| Operation              | Example                            |
|------------------------|------------------------------------|
| Create on GPU          | `torch.tensor(..., device='cuda')` |
| Move to GPU            | `tensor.to("cuda")`                |
| Move to CPU            | `tensor.to("cpu")`                 |
| Move model to GPU      | `model.to("cuda")`                 |
| Check device           | `tensor.device`                    |
| Check GPU availability | `torch.cuda.is_available()`        |

---

> 🔗 Official Docs: [PyTorch CUDA Semantics](https://pytorch.org/docs/stable/notes/cuda.html)

---

In [76]:
torch.cuda.is_available()

False

In [77]:
device = torch.device('cuda')

In [78]:
# Creating a tensor on GPU
a = torch.rand((2, 3), device=device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [79]:
# moving a tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [80]:
b = a.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [81]:
b + 5

tensor([[5.0000, 5.0887, 5.4890],
        [5.5887, 5.7340, 5.8497]])

In [82]:
# comparing CPU and GPU 

import torch
import time

# Defining the size of the tensor
size = 10000 # large size for performance comparison

# Creating a tensor on CPU using rand
a_cpu = torch.rand(size, size)
b_cpu = torch.rand(size, size)

# Measuring time on CPU
start_time_cpu = time.time()
result_cpu = torch.matmul(a_cpu, b_cpu) # matrix multiplication is performed on cPU
cpu_time = time.time() - start_time_cpu

print(f"Time taken on CPU: {cpu_time:.4f} seconds")

# Transferring tenosrs to GPU
a_gpu = a_cpu.to('cuda')
b_gpu = b_cpu.to('cuda')

# Measuring time on GPU
start_time_gpu = time.time()
result_gpu = torch.matmul(a_gpu, b_gpu)  # matrix multiplication is performed on GPU
torch.cuda.synchronize()  # Wait for all kernels in all streams on a GPU to finish
gpu_time = time.time() - start_time_gpu

print(f"Time taken on GPU: {cpu_time:.4f} seconds")

# Comparing the results
print("\nSpeeduo (CPU time / GPU time): ", cpu_time / gpu_time)

Time taken on CPU: 30.9514 seconds


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

# Reshaping Tensors

# 🔄 Reshaping Tensors in PyTorch

Reshaping operations in PyTorch are used to change the shape of a tensor **without changing its data**. These are essential in preprocessing, model input formatting, and data manipulation in deep learning.

---

## 📌 Common Reshaping Operations

---

### 🔹 `tensor.view()`

- Returns a new tensor with the same data but different shape.
- Only works on **contiguous** tensors.

```
x = torch.randn(2, 3, 4)
y = x.view(6, 4)  # reshapes to (6, 4)
```

> ⚠️ `view()` may fail if the tensor is not contiguous. Use `tensor.contiguous()` before applying it if needed.

---

### 🔹 `tensor.reshape()`

- Similar to `view()` but more flexible.
- Can handle non-contiguous tensors.

```
x = torch.randn(2, 3, 4)
y = x.reshape(6, 4)  # reshapes to (6, 4)
```

---

### 🔹 `tensor.flatten()`

- Flattens a multi-dimensional tensor into a 1D tensor.
- You can also flatten only part of the dimensions.

```
x = torch.randn(2, 3, 4)
x_flat = x.flatten()        # shape: (24,)
x_flat_1 = x.flatten(start_dim=1)  # shape: (2, 12)
```

---

### 🔹 `tensor.unsqueeze(dim)`

- Adds a dimension of size `1` at the specified position.

```
x = torch.tensor([1.0, 2.0, 3.0])  # shape: (3,)
x_unsq = x.unsqueeze(0)           # shape: (1, 3)
x_unsq2 = x.unsqueeze(1)          # shape: (3, 1)
```

---

### 🔹 `tensor.squeeze(dim)`

- Removes all dimensions of size `1`.

```
x = torch.randn(1, 3, 1, 5)
x_squeezed = x.squeeze()     # removes all dimensions of size 1: shape (3, 5)
x_squeezed_1 = x.squeeze(0)  # removes dim 0 if it is 1
```

---

### 🔹 `tensor.permute(dims)`

- Permutes (reorders) dimensions of a tensor.

```
x = torch.randn(2, 3, 4)
x_perm = x.permute(1, 0, 2)  # shape: (3, 2, 4)
```

---

### 🔹 `tensor.transpose(dim0, dim1)`

- Swaps two dimensions of a tensor.

```
x = torch.randn(2, 3)
x_t = x.transpose(0, 1)  # shape: (3, 2)
```

---

## 🧠 Shape Inference with `-1`

- `-1` lets PyTorch **automatically calculate** the size of that dimension.

```
x = torch.randn(2, 3, 4)
x_reshaped = x.view(-1, 4)  # shape: (6, 4)
```

---

## 🧪 Example Summary

```
x = torch.randn(2, 3, 4)

x.view(6, 4)           # reshape to (6, 4)
x.reshape(2, 12)       # reshape to (2, 12)
x.flatten()            # flatten to (24,)
x.unsqueeze(0)         # add dimension: (1, 2, 3, 4)
x.squeeze()            # remove size 1 dims
x.permute(2, 0, 1)     # reorder to (4, 2, 3)
x.transpose(0, 1)      # swap first two dims
```

---

> 🔗 **Docs Reference**: [PyTorch Tensor Operations](https://pytorch.org/docs/stable/tensors.html)

---


In [ ]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
# a.reshape(2, 2, 2, 2)
a.reshape(2, 8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.3084, 0.2497, 0.5905, 0.9444],
         [0.9316, 0.0869, 0.5337, 0.6454],
         [0.2783, 0.1392, 0.3548, 0.3154]],

        [[0.7155, 0.8725, 0.3784, 0.9932],
         [0.8321, 0.4904, 0.5448, 0.8393],
         [0.9212, 0.6474, 0.4833, 0.6609]]])

In [ ]:
# permute
b.permute(2, 0, 1).shape


torch.Size([4, 2, 3])

In [ ]:
b

tensor([[[0.3084, 0.2497, 0.5905, 0.9444],
         [0.9316, 0.0869, 0.5337, 0.6454],
         [0.2783, 0.1392, 0.3548, 0.3154]],

        [[0.7155, 0.8725, 0.3784, 0.9932],
         [0.8321, 0.4904, 0.5448, 0.8393],
         [0.9212, 0.6474, 0.4833, 0.6609]]])

In [ ]:
# unsqueeze
c = torch.rand(256, 256, 3)
c.unsqueeze(0).shape

torch.Size([1, 256, 256, 3])

In [ ]:
# squeeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and PyTorch

# 🔄 NumPy Array and PyTorch Tensor Conversion

PyTorch integrates seamlessly with NumPy. You can **convert data between NumPy arrays and PyTorch tensors** without copying data (i.e., sharing memory), which is highly efficient.

---

## 🔁 Convert NumPy Array → PyTorch Tensor

### ✅ Using `torch.from_numpy()`

```
import numpy as np
import torch

np_array = np.array([1, 2, 3, 4])
torch_tensor = torch.from_numpy(np_array)

print(torch_tensor)  # tensor([1, 2, 3, 4])
```

> ⚠️ The resulting tensor **shares memory** with the NumPy array. If one is modified, the other is affected.

---

## 🔁 Convert PyTorch Tensor → NumPy Array

### ✅ Using `tensor.numpy()`

```
torch_tensor = torch.tensor([1, 2, 3, 4])
np_array = torch_tensor.numpy()

print(np_array)  # [1 2 3 4]
```

> ⚠️ Works only if the tensor is on **CPU**. Move to CPU using `.cpu()` if needed.

```python
tensor_on_gpu = torch.tensor([1, 2, 3], device='cuda')
np_array = tensor_on_gpu.cpu().numpy()
```

---

## 🔁 Bidirectional Conversion & Shared Memory

```
# Shared memory example
arr = np.array([10, 20])
ten = torch.from_numpy(arr)
arr[0] = 99
print(ten)  # tensor([99, 20])
```

> 🧠 These conversions are **zero-copy** (no data duplication), unless explicitly told otherwise.

---

## 🧪 Summary Table

| Direction              | Function             | Shared Memory? | Notes                            |
|------------------------|----------------------|----------------|----------------------------------|
| NumPy → Tensor         | `torch.from_numpy()` | ✅ Yes         | Must be contiguous               |
| Tensor → NumPy         | `tensor.numpy()`     | ✅ Yes         | Only on CPU tensors              |
| GPU Tensor → NumPy     | `.cpu().numpy()`     | ❌ No          | Data is copied to CPU            |
| Tensor → NumPy (copy)  | `tensor.detach().cpu().numpy()` | ❌ No | Safe for tensors that require grad |

---

## 🔗 References

- [PyTorch NumPy Bridge Docs](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-between-numpy-and-torch-tensor)


---


In [1]:
import numpy as np
np.__version__

'2.2.5'

In [4]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [5]:
# b = a.cpu().numpy()  # convert tensor to numpy array if tensor is on GPU
b = a.numpy() # convert tensor to numpy array if tensor is on CPU
b

array([1, 2, 3])

In [7]:
type(b)

numpy.ndarray

In [6]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [8]:
torch.from_numpy(c)  # convert numpy array to tensor

tensor([1, 2, 3])