## NN Module

### Neural Network without any Hidden Layer

In [8]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [9]:
# create a dataset
features = torch.rand(10, 5)

# creates a model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.3743],
        [0.3968],
        [0.4755],
        [0.4297],
        [0.3764],
        [0.3937],
        [0.3527],
        [0.4140],
        [0.3837],
        [0.3551]], grad_fn=<SigmoidBackward0>)

In [10]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.3707,  0.4324, -0.3916, -0.2692, -0.0089]], requires_grad=True)

In [11]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.0778], requires_grad=True)

In [12]:
!pip install torchinfo


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [13]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Neural Network with any Hidden Layer

In [ ]:
import torch
import torch.nn as nn

In [14]:
class ModelwithHiddenLayer(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out
    

In [16]:
# creates dataset
features = torch.rand(10, 5)

# create model
model = ModelwithHiddenLayer(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3503],
        [0.3458],
        [0.3480],
        [0.3370],
        [0.3514],
        [0.3476],
        [0.3573],
        [0.3586],
        [0.3510],
        [0.3613]], grad_fn=<SigmoidBackward0>)

In [19]:
# show model weights
# model.linear1.weight
model.linear2.weight

Parameter containing:
tensor([[ 0.0423,  0.3623, -0.2313]], requires_grad=True)

In [22]:
# show model bias
# model.linear1.bias
model.linear2.bias

Parameter containing:
tensor([-0.5742], requires_grad=True)

In [23]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
ModelwithHiddenLayer                     [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Sequential Container

In [24]:
class ModelwithHiddenLayer(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)

        return out
    

In [25]:
# creates dataset
features = torch.rand(10, 5)

# create model
model = ModelwithHiddenLayer(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3338],
        [0.3584],
        [0.3697],
        [0.3685],
        [0.3665],
        [0.3459],
        [0.3944],
        [0.3336],
        [0.3523],
        [0.3513]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Inspecting the Model
model.network

In [37]:
# show model weights 

# model.network[0].weight  # Weights of the first Linear layer
model.network[2].weight  # Weights of the second Linear layer


Parameter containing:
tensor([[-0.1998,  0.4892, -0.2644]], requires_grad=True)

In [36]:
# show model bias

model.network[0].bias    # Bias of the first Linear layer
# model.network[2].bias    # Bias of the second Linear layer

Parameter containing:
tensor([ 0.1363, -0.0318,  0.3949], requires_grad=True)

In [38]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
ModelwithHiddenLayer                     [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00