## Dataset and Dataloader

In [23]:
from sklearn.datasets import make_classification
import torch

In [24]:
# Step1: Create a synthetic dataset using sklearn
X, y = make_classification(
    n_samples=10,  # Number of samples
    n_features=5,  # Number of features
    n_informative=2,  # Number of informative features
    n_redundant=0,  # Number of redundant features
    n_classes=2,  # Number of classes
    random_state=42  # Random seed for repoducibility
)

In [25]:
X.shape

(10, 5)

In [26]:
y.shape

(10,)

In [27]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [28]:
X

tensor([[-1.4785,  1.0683, -0.4606, -0.7198, -0.9701],
        [-1.3282, -1.1402,  0.7385,  0.1969, -0.8388],
        [-0.0135, -0.7206,  0.8225, -1.0577, -0.9606],
        [ 0.1714, -0.9382, -0.3011, -0.1156, -0.5430],
        [ 1.0571,  1.7273, -1.7630,  0.3436, -1.1858],
        [-1.2208, -0.5872, -1.9597,  0.2089, -1.9717],
        [ 0.6117, -2.8954,  0.9313,  1.0310,  1.9769],
        [ 0.9755,  1.8997, -0.1857, -0.4792,  0.8344],
        [-0.8392,  1.7774,  0.3313, -0.3092,  1.5116],
        [ 0.3241, -1.9629, -0.6769, -0.3851, -0.9923]])

In [29]:
y

tensor([1, 0, 0, 1, 1, 0, 0, 1, 1, 0])

In [30]:
from torch.utils.data import Dataset, DataLoader

In [31]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [32]:
dataset = CustomDataset(X, y)

In [33]:
len(dataset)

10

In [34]:
dataset[2]

(tensor([-0.0135, -0.7206,  0.8225, -1.0577, -0.9606]), tensor(0))

In [35]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[ 0.3241, -1.9629, -0.6769, -0.3851, -0.9923],
        [-0.8392,  1.7774,  0.3313, -0.3092,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.2208, -0.5872, -1.9597,  0.2089, -1.9717],
        [ 0.6117, -2.8954,  0.9313,  1.0310,  1.9769]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.0571,  1.7273, -1.7630,  0.3436, -1.1858],
        [-0.0135, -0.7206,  0.8225, -1.0577, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 0.1714, -0.9382, -0.3011, -0.1156, -0.5430],
        [-1.3282, -1.1402,  0.7385,  0.1969, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 0.9755,  1.8997, -0.1857, -0.4792,  0.8344],
        [-1.4785,  1.0683, -0.4606, -0.7198, -0.9701]])
tensor([1, 1])
--------------------------------------------------
